### PR TITLE
refact acquisition: build profiles (optionally exclude datasources from final binary)

### PR DESCRIPTION
**Pull request by mmetc**

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Just to ask a question instead of determining `"minimal"` shouldnt we create it so users have to define the build flags by default? yes it will break third partys but they can patch it no? as I see users maybe wanting to create a "docker" acquisition only build or something which they cannot do from this.

**Comment by mmetc** [comment]
> Just to ask a question instead of determining `"minimal"` shouldnt we create it so users have to define the build flags by default? yes it will break third partys but they can patch it no? as I see users maybe wanting to create a "docker" acquisition only build or something which they cannot do from this.
> 
> Yes, its an edge case which they can patch there own Makefile but 🤷🏻

I'm rewriting that part.

**Comment by mmetc** [comment]
@LaurenceJJones better now?

**Review by sabban — APPROVED** [review]
lgtm

**Comment by mmetc** [comment]
If we merge this, I'll remove "EXCLUDE_MEDIUM", it was just an example.

**Review by blotus — APPROVED** [review]

**Pull request merged**
