### PR TITLE
Add unix expr helper

### LINKED ISSUE #1950: EXPR Helper Unix -> Datetime stamp
### What would you like to be added?

Expr helper to convert unix timestamp to our datetime stamp for enrichment

/kind enhancement

### Why is this needed?

If there is no other timestamp cold log / time machine mode will never work

### PR DESCRIPTION
**Pull request by LaurenceJJones**
Fix #1950

### CODE REVIEW

**Review by AlteredCoder — APPROVED** [review]

**Comment by mmetc** [comment]
Is it Date or DateTime?

**Review by buixor — APPROVED** [review]
lgtm

**Comment by LaurenceJJones** [comment]
@mmetc Thoughts on tests?

**Comment by mmetc** [comment]
> @mmetc Thoughts on tests?

maybe overflow: 32bit, 64bit, negative values

**Pull request merged**
