### PR TITLE
Update sprig to v3

### PR DESCRIPTION
**Pull request by LaurenceJJones**
#1721 Update sprig version dependency

### CODE REVIEW

**Comment by sabban** [comment]
Hi @LaurenceJJones,

Sorry for the delay. This wasn't merged yet because there was an issue on our side that prevented the ci tests to pass. Can you rebase this against master (or at least fix the conflicts that appeared) ? I guess, there're no issue fr this to be merged, Sprigv3 doesn't seem to change already existing behaviors.

Thank you

**Comment by LaurenceJJones** [comment]
Hey, I fixed the merge conflicts, however, there was more cause kafka-go was not a direct package?

**Comment by LaurenceJJones** [comment]
@sabban Think I was missing the hardcoded db creds and the tests are passing now 👍🏻

**Review by sabban — APPROVED** [review]
lgtm
Sprigv3 upgrade doesn't change any old behaviour

**Pull request merged**
