### PR TITLE
docker: add {VERSION}-slim tag to releases

### PR DESCRIPTION
**Pull request by mmetc**

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Fix #1974 link to original issue

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Comment by thespad** [comment]
The slim version is only getting pushed to DH and not GHCR. See:

https://github.com/crowdsecurity/crowdsec/actions/runs/4004244996/jobs/6873137788#step:8:2735 for the slim image vs

https://github.com/crowdsecurity/crowdsec/actions/runs/4004244996/jobs/6873137788#step:9:656 for the full image.

**Pull request merged**
