### PR TITLE
print cscli usage in color, fix windows terminal detection

### PR DESCRIPTION
**Pull request by mmetc**
With this, usage of cscli is colored except when in a pipe (tested linux, windows cmd, powershell 7.x).
Same behavior with the tables, and if color is disabled, so are unicode characters.
I took the opportunity to reorganize the imports in cmd/crowdsec-cli

Screenshot from 2022-10-12 16-59-45

### CODE REVIEW

**Review by wojtekxtx — APPROVED** [review]
LGTM :)

**Review by wojtekxtx — COMMENTED** [review]
Good, but make `CI/CI` build `pass`

**Comment by crowdsec-cu-auto** [comment]
Thank you for creating an issue, a notification have been sent to the team.

**Review by sabban — APPROVED** [review]
lgtm

**Pull request merged**
