### PR TITLE
Removing not needed files

### PR DESCRIPTION
**Pull request by wojtekxtx**

### CODE REVIEW

**Comment by mmetc** [comment]
Aren't these used in the acquisition tests?

**Comment by wojtekxtx** [comment]
@mmetc dont think so

**Comment by mmetc** [comment]
```
 FAIL | LoadAcquisitionFromFile (0.00s)
     |     acquisition_test.go:290: invalid_yaml_file : expected error 'failed to yaml decode test_files/badyaml.yaml: yaml: unmarshal errors' in 'can't open test_files/badyaml.yaml: open test_files/badyaml.yaml: no such file or directory'
```

The unit tests are run in github CI, if you want to check in your environment:

shell 1 -> make localstack (requires docker, docker-compose)
shell 2 -> make test

**Comment by wojtekxtx** [comment]
@mmetc are you talking to me?

**Comment by mmetc** [comment]
Removing not needed user.

**Pull request closed without merging**
