### PR TITLE
Added steps for proxy on systemd service

### PR DESCRIPTION
**Pull request by Lamera**
I solved my issue with these steps and I think these steps are needed in the documentation.

### CODE REVIEW

**Comment by AlteredCoder** [comment]
Hello @Lamera , thanks for your contribution!

**Review by AlteredCoder — APPROVED** [review]

**Comment by blotus** [comment]
Hello @Lamera,

Would it be possible to document this using an override file instead of modifying the unit file directly ?

**Review by sabban — APPROVED** [review]
lgtm

**Comment by he2ss** [comment]
Thx @Lamera for your contribution !

**Pull request merged**
