### PR TITLE
allow Makefile to override /etc/crowdsec and /var/lib/crowdsec/data

### PR DESCRIPTION
**Pull request by mmetc**
fix for https://github.com/crowdsecurity/crowdsec/issues/1162

### CODE REVIEW

**Comment by erdoukki** [comment]
Great add-on…
I need it !
I will test it to see if it help me as planned.
Thanks

**Review by erdoukki — APPROVED** [review]
Thanks

**Review by buixor — APPROVED** [review]
great :)

**Comment by erdoukki** [comment]
https://github.com/crowdsecurity/crowdsec/pull/1224

**Pull request merged**
