### PR TITLE
Add postgresql sslmode option

### PR DESCRIPTION
**Pull request by svesve**
Add postgresql sslmode option, fix spaces in docs

### CODE REVIEW

**Comment by buixor** [comment]
Hello,

Thanks for the merge request, let's have a look at this :+1:

**Comment by svesve** [comment]
Hello! Have u look this merge? PG sslmode option is very useful, because by default postgresql works wthout ssl

**Comment by svesve** [comment]
@buixor yes i've try ssl + pgsql and this is a big trouble for quick start to use crowdsec + pg batabase
1. You need to generate selfsigned ssl certificate, bcs 99% postgressql instances use ip instead of FQDN
2. In most case, users have already worked postgresql instances without ssl
So, I think sslmode option is important part of this project.

**Comment by buixor** [comment]
Thanks for the suggestion, and I agree it's important for the project. However if I'm not mistaken your patch doesn't set a default value, so it will break existing installs with postgresql no ?

**Comment by svesve** [comment]
It can't brake existing install, you must define sslmode in config file, like a host, port and etc..

**Comment by buixor** [comment]
> It can't brake existing install, you must define sslmode in config file, like a host, port and etc..

Yes, I was actually afraid that someone upgrading without defining `sslmode` will end up with invalid connection string and break install. But I tried locally and it seems good, so we're good to merge.

Thanks !

**Comment by buixor** [comment]
Sorry for the delay, and thanks !

**Pull request merged**
