### PR TITLE
Update grammar of index.md for localAPI docs

### PR DESCRIPTION
**Pull request by kingmilo**
A few grammar updates to the index.md file within the localAPI docs.

### CODE REVIEW

**Comment by AlteredCoder** [comment]
Hello @kingmilo , thanks for your contribution, i approve your changes :)

**Comment by kingmilo** [comment]
Hi @AlteredCoder, you're welcome! I'll go through the rest of the docs during the week and see where I can add value :)

**Review by AlteredCoder — APPROVED** [review]

**Comment by AlteredCoder** [comment]
Thanks you @kingmilo :)

**Comment by kingmilo** [comment]
Thank you @AlteredCoder :)

**Pull request merged**
