### PR TITLE
Implement reinject command to send notifications of alerts

### PR DESCRIPTION
**Pull request by sabban**
* add a way to test notifications with cscli

### CODE REVIEW

**Comment by buixor** [comment]
@sabban : Can you add some doc to crowdsec-docs to accompany this plz ? thanks :)

**Comment by buixor** [comment]
few feedbacks playing around with the feature !

 - `notifications inspect`: the output currently looks like this :

image

It might be interesting to link the relevant paths to the user rather than just dumping the content. As well, the formatting of the config content looks a bit awkward.

 - `notifications reinject`: I didn't manage to make the feature work

```
./cscli -c dev.yaml alerts list
+----+-------------+----------------------+---------+----+-----------+--------------------------------+
| ID |    VALUE    |        REASON        | COUNTRY | AS | DECISIONS |           CREATED AT           |
+----+-------------+----------------------+---------+----+-----------+--------------------------------+
|  1 | Ip:1.2.3.42 | crowdsecurity/ssh-bf | AU      | 0  | ban:1     | 2022-07-29 12:30:50.590639512  |
|    |             |                      |         |    |           | +0000 UTC                      |
+----+-------------+----------------------+---------+----+-----------+--------------------------------+
./cscli -c dev.yaml notifications reinject 1
DEBU[0000] starting plugin                               args="[/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack]" path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack
DEBU[0000] plugin started                                path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack pid=581676
DEBU[0000] waiting for RPC address                       path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack
DEBU[0000] using plugin                                  version=1
TRAC[0000] waiting for stdio data                       
INFO[29-07-2022 02:36:36 PM] registered plugin slack_default              
INFO[29-07-2022 02:36:36 PM] The profile default_ip_remediation didn't match 
INFO[29-07-2022 02:36:36 PM] plugingTomb dying                            
INFO[29-07-2022 02:36:36 PM] killing all plugins                          
DEBU[0000] received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = error reading from server: EOF"
DEBU[0000] plugin process exited                         path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack pid=581676
DEBU[0000] plugin exited                                




```

**Comment by sabban** [comment]
> few feedbacks playing around with the feature !
> 
>     * `notifications inspect`: the output currently looks like this :
> 
> 
> image
> 
> It might be interesting to link the relevant paths to the user rather than just dumping the content. As well, the formatting of the config content looks a bit awkward.

This should be taken care of in a other PR. 

>     * `notifications reinject`: I didn't manage to make the feature work, the alert fetched from the database has `Remediation` set to false and thus doesn't match the default profile.
> 
> 
> ```
> ./cscli -c dev.yaml alerts list
> +----+-------------+----------------------+---------+----+-----------+--------------------------------+
> | ID |    VALUE    |        REASON        | COUNTRY | AS | DECISIONS |           CREATED AT           |
> +----+-------------+----------------------+---------+----+-----------+--------------------------------+
> |  1 | Ip:1.2.3.42 | crowdsecurity/ssh-bf | AU      | 0  | ban:1     | 2022-07-29 12:30:50.590639512  |
> |    |             |                      |         |    |           | +0000 UTC                      |
> +----+-------------+----------------------+---------+----+-----------+--------------------------------+
> ./cscli -c dev.yaml notifications reinject 1
> DEBU[0000] starting plugin                               args="[/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack]" path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack
> DEBU[0000] plugin started                                path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack pid=581676
> DEBU[0000] waiting for RPC address                       path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack
> DEBU[0000] using plugin                                  version=1
> TRAC[0000] waiting for stdio data                       
> INFO[29-07-2022 02:36:36 PM] registered plugin slack_default              
> INFO[29-07-2022 02:36:36 PM] The profile default_ip_remediation didn't match 
> INFO[29-07-2022 02:36:36 PM] plugingTomb dying                            
> INFO[29-07-2022 02:36:36 PM] killing all plugins                          
> DEBU[0000] received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = error reading from server: EOF"
> DEBU[0000] plugin process exited                         path=/home/bui/github/crowdsec/crowdsec-v1.4.1/tests/plugins/notification-slack pid=581676
> DEBU[0000] plugin exited                                
> ```

I guess it's the expected behaviour then. The alert is reinjected only if the profile is matched.

**Review by buixor — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you
I tested this with the Docker version and it works fine !

Config: https://github.com/datacenters-network/mails/blob/8122eafdc9527c9941aae2af8777434067035029/crowdsec/notifications/telegram.yaml

I am not sure about: `received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = error reading from server: EOF`
```
DEBU[0000] starting plugin                               args="[/usr/local/lib/crowdsec/plugins/notification-http]" path=/usr/local/lib/crowdsec/plugins/notification-http
DEBU[0000] plugin started                                path=/usr/local/lib/crowdsec/plugins/notification-http pid=118
DEBU[0000] waiting for RPC address                       path=/usr/local/lib/crowdsec/plugins/notification-http
DEBU[0000] using plugin                                  version=1
TRAC[0000] waiting for stdio data                       
INFO[09-11-2022 04:39:50 PM] registered plugin http_default               
INFO[09-11-2022 04:39:50 PM] The profile default_ip_remediation matched, sending to its configured notification plugins 
INFO[09-11-2022 04:39:50 PM] sleeping                                     
INFO[09-11-2022 04:39:50 PM] The profile default_ip_remediation contains a 'on_success: break' so bailing out 
INFO[09-11-2022 04:39:50 PM] pluginTomb dying                             
INFO[0000] received signal for http_default config       @module=http-plugin
INFO[09-11-2022 04:39:50 PM] killing all plugins                          
DEBU[0000] received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = error reading from server: EOF"
DEBU[0000] plugin process exited                         path=/usr/local/lib/crowdsec/plugins/notification-http pid=118
DEBU[0000] plugin exited  
```

**Pull request merged**
