### PR TITLE
try to make reproducible build work

### PR DESCRIPTION
**Pull request by sabban**
Small change to make debian reproducible build work

### CODE REVIEW

**Review by blotus — APPROVED** [review]

**Comment by CyrilBrulebois** [comment]
Without this, I'm getting a failure to build (during the test suite) when setting back the clock to 2022-01-01; with this patch applied on top of the 1.4.6-1 Debian package, the test suite passes. I'm not confident (yet) this is going to be sufficient to fix build failures in the reproducible-builds.org environment, but this is definitely going to help! I should have more data once 1.4.6-2 gets uploaded, and build-tested there.

**Comment by CyrilBrulebois** [comment]
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/crowdsec.html says things are looking good now:

> reproducible 1.4.6-3 in unstable
> at 2023-03-19 05:38:00 UTC

**Pull request merged**
