### PR TITLE
Fix docker_start.sh not properly handling env vars (backport)

### PR DESCRIPTION
**Pull request by mmetc**

### CODE REVIEW

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Comment by LaurenceJJones** [comment]
Note that this includes the slim tag fix?

**Comment by LaurenceJJones** [comment]
Note that this includes the slim tag fix?

**Comment by mmetc** [comment]
> Note that this includes the slim tag fix?

Yes, I have not squashed.

**Pull request merged**
