### PR TITLE
Store go module name in var in Makefile

### PR DESCRIPTION
**Pull request by junnhy5**
For a question of cleanliness and if the project will evolve in the future at the level of the not (even if there is little chance that it is the case), to store the name of the module in a variable and call it then. 😊

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
/are configuration
/kind enhancement

Thank you for the pull request! yes this can be merged. Thank you!

**Comment by junnhy5** [comment]
@LaurenceJJones merging is blocked by the CI 😌

**Comment by mmetc** [comment]
GO_MODULE_NAME = "github.com/crowdsecurity/crowdsec"

you have to remove the quotes: GO_MODULE_NAME=github...

**Review by mmetc — APPROVED** [review]

**Pull request merged**
