### PR TITLE
notification-email: configurable timeouts

### PR DESCRIPTION
**Pull request by mmetc**
https://github.com/crowdsecurity/crowdsec/issues/2463

Expose the timeout options to the user but allow send as well as connect incase user wants both

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
@mmetc just move ahead with this impl

/kind enhancement
/area agent

**Comment by LaurenceJJones** [comment]
impl #2463

**Review by LaurenceJJones — COMMENTED** [review]
add configuration example to email.yaml so they know what keys look like even if commented

**Review by buixor — APPROVED** [review]

**Comment by mmetc** [comment]
> add configuration example to email.yaml so they know what keys look like even if commented

Done. However, you were right in using a duration string because we already have a "timeout" option in the generic plugin settings, which we parse as duration. So it's better to stay consistent :/

**Comment by LaurenceJJones** [comment]
> > add configuration example to email.yaml so they know what keys look like even if commented
> 
> Done. However, you were right in using a duration string because we already have a "timeout" option in the generic plugin settings, which we parse as duration. So it's better to stay consistent :/

Yeah, and I thought creating a nested yaml statement allows a user to easily see this is for email, not the plugin timeouts

**Comment by mmetc** [comment]
I see your point but all the other mail-specific options are at the same level. I think the comment in the config example is enough. I added "helo_host" which was missing.

**Comment by mmetc** [comment]
I'll merge after updating docs in https://docs.crowdsec.net/docs/next/notification_plugins/email

**Pull request merged**
