### PR TITLE
refresh API Swagger model

### PR DESCRIPTION
**Pull request by AlteredCoder**
Question:

 - Do we still want to have the route for deleting watchers?
 - Do we still want to the `/ping` route ?

### CODE REVIEW

**Comment by erenJag** [comment]
For me,
* we should delete the method that allow a watcher to delete himself because there is no logical user story in our context to permit that.
* `/ping` can be deleted too (unused).

Don't forget to regenerate the models with this new swagger file.

**Comment by buixor** [comment]
> * we should delete the method that allow a watcher to delete himself because there is no logical user story in our context to permit that.

I think for multi-machines setup (one APIL, several Crowdsec) it makes sense. And it can make sense as well at the APIC level and could be called when the user uninstalls crowdsec.

**Comment by erenJag** [comment]
oh yes my bad, so agree for watchers deletion.

**Comment by buixor** [comment]
deprecated done by other MR

**Pull request closed without merging**
