### PR TITLE
cscli config test

### PR DESCRIPTION
**Pull request by LaurenceJJones**
#1624 Implementation

Looking forward to hearing some feedback on this.

### CODE REVIEW

**Comment by sabban** [comment]
Hi @LaurenceJJones,

Sorry  for the delay.

I guess you want to way for cscli to check crowdsec configuration which is a good idea. OTOH this relies on the PATH and the "crowdsec" name to work, which is I guess, not possible to assume in every case.

For this feature I would have used the same code as in crowdsec using the `StartRunSvc` function with the `LintOnly`flag of Crowdsec configuration struct set to true. But it would raised another issue: that we duplicate code between crowdsec and cscli. So I would say this needs more thinking.

@buixor @sblot any more thoughts ?

Thanks for the contribution !

**Comment by sabban** [comment]
Maybe we should document `crowdsec -t` as well

**Comment by buixor** [comment]
As discussed, it might make more sense to simply improve `crowdsec -t` rather than adding some glue around it.
Keeping it opened till we all agree to close it, but removing milestone.

**Comment by LaurenceJJones** [comment]
Conclusion update docs around `crowdsec -t`, install into users before `systemctl restart crowdsec` best practice to run this command and check logs.

**Pull request closed without merging**
