### PR TITLE
[postoverflow] Reinject meta into overflown state

### PR DESCRIPTION
**Pull request by LaurenceJJones**
#1337

This one is difficult to find an appropriate fix..... since Meta is converted to events on "overflow" anything set in meta in postoverflow stage is never carried beyond. This PR re injects all meta objects across all events, to make sure the user has it.

I am primarily looking for feedback as I couldnt really see any other property without creating a new one but we already have too many "meta" properties.

### CODE REVIEW

**Review by sabban — COMMENTED** [review]
lgtm

**Review by sabban — COMMENTED** [review]
lgtm

**Review by sabban — APPROVED** [review]
lgtm

**Comment by LaurenceJJones** [comment]
Closing for now due to concerns that re injecting the meta without any consideration from user perspective could cause confusion as we should control which alert in the post overflown is injected.

**Pull request closed without merging**
