### PR TITLE
Add options to disable sharing and receiving from CAPI

### PR DESCRIPTION
**Pull request by LaurenceJJones**
Added two option to disable sharing and receiving from CAPI

This is useful if you want to send signals but not receive and the other way around for premium console users.

### CODE REVIEW

**Review by mmetc — COMMENTED** [review]
Can you avoid using pointers for the bools? If you want the default to be zero value, which makes sense, you can reverse the logic and have
 NoShareSignals and NoCommunityBlocklist.

**Comment by LaurenceJJones** [comment]
> NoShareSignals and NoCommunityBlocklist

DisableSharingSignals and DisableCommunityBlocklists rather than no but I agree.

**Comment by LaurenceJJones** [comment]
Closing PR creating an issue

**Pull request closed without merging**
