### PR TITLE
[wip] Disable a scenario/parser without tainting a collection

### PR DESCRIPTION
**Pull request by AlteredCoder**
Fix https://github.com/crowdsecurity/crowdsec/issues/1348

Note: Currently, `cscli <item_type> remove` doesn't really remove an item but disable it (we need to provide `--purge` to remove the item).

- Don't consider a collection as tainted if we have remove it without `--purge`

TODO: check behavior on item or collection upgrade

### CODE REVIEW

**Comment by buixor** [comment]
@AlteredCoder : yes I think upgrade needs to be tested

**Comment by Lamera** [comment]
What happens with CAPI decisions, from removed scenarios? Are they applied anyway?

**Comment by he2ss** [comment]
@Lamera if you decide to disable a scenario, so there will not be a new decisions triggered by this scenario anymore.
This PR purpose is just to avoid having a collection is state `tainted` when a scenario is only disabled and not customized.

**Comment by buixor** [comment]
we're going to revamp cwhub and hence we don't want to invest more time on fixing the current code

**Pull request closed without merging**
