### PR TITLE
GetExprEnv usage optimization

### PR DESCRIPTION
**Pull request by nitescuc**
`GetExprEnv` is provided to `expr` evaluation very often. Try to cache it to improve performance

### CODE REVIEW

**Comment by nitescuc** [comment]
> @nitescuc : where you able to check that caching the context in the parser doesn't "hide" changes made by parsers ? (ie. parser-1 modifies the object, parser-2 should get the modified object)

No, I just did a simple test. I'm not quite comfortable with the scenario you describe with my current crowdsec knowledge :-)

**Comment by buixor** [comment]
> > @nitescuc : where you able to check that caching the context in the parser doesn't "hide" changes made by parsers ? (ie. parser-1 modifies the object, parser-2 should get the modified object)
> 
> No, I just did a simple test. I'm not quite comfortable with the scenario you describe with my current crowdsec knowledge :-)

Somehow, if `cscli hubtests` are running correctly with this change, it is fine :+1:

**Comment by nitescuc** [comment]
> > > @nitescuc : where you able to check that caching the context in the parser doesn't "hide" changes made by parsers ? (ie. parser-1 modifies the object, parser-2 should get the modified object)
> > 
> > 
> > No, I just did a simple test. I'm not quite comfortable with the scenario you describe with my current crowdsec knowledge :-)
> 
> Somehow, if `cscli hubtests` are running correctly with this change, it is fine 👍

cscli hubtest run show no error

**Review by sabban — APPROVED** [review]
lgtm

**Pull request merged**
